### ISSUE TITLE
Small mobile issue

### ISSUE THREAD

**Issue by developess** [fac-14/Week3TakingAIME#27]
I just noticed that on mobile (at least when looking via dev tools) The drop down loses its styling and its hard to tell that its a drop down? Just looks like paragraph text. See pic:

![screen shot 2018-07-20 at 10 25 02](https://user-images.githubusercontent.com/31890915/42994841-2f445f50-8c07-11e8-81d0-67b1d92bdcce.png)

**Comment by sima-qian** [comment]
This is a strange bug that we also noticed -- but it didn't seem to show up on actual mobiles.
