### ISSUE TITLE
Colour consistency

### ISSUE THREAD

**Issue by samhstn** [fac-14/Week3TakingAIME#31]
If you use colour hex codes in one place, I would try if possible to stick with using hex codes.

You have used hex code notation [here](https://github.com/fac-14/Week3TakingAIME/blob/master/logic.js#L95), but rgba [here](https://github.com/fac-14/Week3TakingAIME/blob/master/logic.js#L113)

**Comment by MissArray** [comment]
Yep, thanks for pointing this out.

**Comment by sbinlondon** [comment]
All sorted! Thanks @samhstn

**Comment by samhstn** [comment]
This doesn't look fixed, https://github.com/fac-14/Week3TakingAIME/blob/master/logic.js#L112
