### ISSUE TITLE
Use of ES6 ("let")

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/Week3TakingAIME#32]
ES6 BANNED

https://github.com/fac-14/Week3TakingAIME/blob/8cc43ff486ae7877229d489924a643a851abf80b/logic.js#L21

**Comment by vlbee** [comment]
Also, let and const are not (yet) fully supported on all browsers. We need think of the IE and Opera users still I'm afraid! 
https://caniuse.com/#search=let

**Comment by sima-qian** [comment]
IE users can burn in hell for their sins.

**Comment by sima-qian** [comment]
Fixed on Code-review-changes branch

**Comment by sima-qian** [comment]
Fixed in #42
