### ISSUE TITLE
Un-Accessibility 

### ISSUE THREAD

**Issue by vlbee** [fac-14/Week3TakingAIME#33]
By removing your :focus outlines in your CSS, you have made your site unaccessible to anyone who needs to use a keyboard for navigation.  

https://github.com/fac-14/Week3TakingAIME/blob/master/style.css#L99-L106
![image](https://user-images.githubusercontent.com/32312712/42995322-77285a00-8c08-11e8-98bc-87e59031260c.png)

Tip: If you have problems with the way outlines look by browser default, they can also be styled with CSS 😉

**Comment by sima-qian** [comment]
Shit, I thought the outline was just a cosmetic feature and I didn't like the clashing colours. Who built the internet this way!?

We'll fix this.

**Comment by MissArray** [comment]
Thanks for raising this.

Apparently, if an outline is really undesirable, there are alternative ways of improving accessibility:
http://www.outlinenone.com/

**Comment by sima-qian** [comment]
Fixed on Code-review -fixes branch

**Comment by sima-qian** [comment]
Fixed in #42
