### ISSUE TITLE
Let syntax

### ISSUE THREAD

**Issue by samhstn** [fac-14/Week3TakingAIME#34]
Be careful with using `let` syntax. You should instead use `var` ([here](https://github.com/fac-14/Week3TakingAIME/blob/master/logic.js#L60) for example).

**Comment by sima-qian** [comment]
Oops! I recently did the ES6 section on freeCodeCamp so quite enthusiastic at the moment.

**Comment by MissArray** [comment]
Agree, thanks.

**Comment by sima-qian** [comment]
Fixed on Code-review-fixes branch

**Comment by sima-qian** [comment]
Fixed in #42

**Comment by samhstn** [comment]
There's still a `let` here: https://github.com/fac-14/Week3TakingAIME/blob/c6ffd81f55f60670aa2485adf26621e166fbfb66/logic.js#L28

**Comment by sima-qian** [comment]
Bugger.
