### ISSUE TITLE
No indication of issue if API not working?

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/Week3TakingAIME#35]
Did a quick test where I locally edited the TFL API URL to make it return a 404.
The page still changes colour, no line status or gif appears, as expected, but there's no message to tell me that there's been a 404, so I don't know if the site is broken or if it's the API that's down. Maybe you could generate a sad gif to accompany a "TFL API not working" error message!

Similarly, if I mess up the giphy API key, I get the line status and no gif appears, but there's no indication that there was an error. I guess if you're extra keen, you could have an object of backup gif URLs for each line status which runs whenever there's an issue with the giphy API/key

**Comment by sima-qian** [comment]
Good point!

**Comment by sima-qian** [comment]
Fixed in #42
